services:
  mongo:
    image: mongo:latest
    container_name: user_mongo_container
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=kavish.r
      - MONGO_INITDB_ROOT_PASSWORD=5okwJRZDoKcNdXQn
      - MONGO_INITDB_DATABASE=user
    networks:
      - "user-network"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    container_name: user_redis_container
    ports:
      - "6378:6379"
    networks:
      - "user-network"
networks:
  user-network:
    driver: bridge
volumes:
  mongo-data:
    driver: local
