server:
  port: 8081
mongo:
  data:
    app: FlickStreamCluster01
#    user: kavish.r
#    pass: 5okwJRZDoKcNdXQn
    user: kavish2
    pass: 1234
    cluster: flickstreamcluster01.6iqkd
    database:
      name: flickstream_user
    collection: user_data

spring:
  data:
    mongodb:
      uri: mongodb+srv://${mongo.data.user}:${mongo.data.pass}@${mongo.data.cluster}.mongodb.net/${mongo.data.database.name}?retryWrites=true&w=majority&appName=${mongo.data.app}
      database: ${mongo.data.database.name}
